[program:cloudflared]
command=cloudflared tunnel --config %(ENV_HOME)s/.cloudflared/config.yml run %(ENV_CLOUDFLARED_TUNNEL_NAME)s
directory=%(ENV_HOME)s/projects/roxabi-live
environment=HOME="%(ENV_HOME)s",PATH="%(ENV_PATH)s",CLOUDFLARED_TUNNEL_NAME="%(ENV_CLOUDFLARED_TUNNEL_NAME)s"
user=mickael
priority=200
autostart=false
autorestart=false
startsecs=5
startretries=3
stopwaitsecs=10
stopasgroup=true
killasgroup=true
stdout_logfile=%(ENV_HOME)s/.local/state/roxabi-live/logs/cloudflared.out.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile=%(ENV_HOME)s/.local/state/roxabi-live/logs/cloudflared.err.log
stderr_logfile_maxbytes=5MB
stderr_logfile_backups=3
