export const ErrorCode = {
  // RBAC
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_SLUG_CONFLICT: 'ROLE_SLUG_CONFLICT',
  DEFAULT_ROLE_CONSTRAINT: 'DEFAULT_ROLE_CONSTRAINT',
  OWNERSHIP_CONSTRAINT: 'OWNERSHIP_CONSTRAINT',
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  ROLE_INSERT_FAILED: 'ROLE_INSERT_FAILED',
  // Tenant
  TENANT_CONTEXT_MISSING: 'TENANT_CONTEXT_MISSING',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  // Consent
  CONSENT_NOT_FOUND: 'CONSENT_NOT_FOUND',
  CONSENT_INSERT_FAILED: 'CONSENT_INSERT_FAILED',
  ACCOUNT_SCHEDULED_FOR_DELETION: 'ACCOUNT_SCHEDULED_FOR_DELETION',
  ACCOUNT_ALREADY_DELETED: 'ACCOUNT_ALREADY_DELETED',
  ACCOUNT_NOT_DELETED: 'ACCOUNT_NOT_DELETED',
  EMAIL_CONFIRMATION_MISMATCH: 'EMAIL_CONFIRMATION_MISMATCH',
  // Organization
  ORG_NOT_FOUND: 'ORG_NOT_FOUND',
  ORG_SCHEDULED_FOR_DELETION: 'ORG_SCHEDULED_FOR_DELETION',
  ORG_NOT_DELETED: 'ORG_NOT_DELETED',
  ORG_NAME_CONFIRMATION_MISMATCH: 'ORG_NAME_CONFIRMATION_MISMATCH',
  ORG_NOT_OWNER: 'ORG_NOT_OWNER',
  TRANSFER_TARGET_NOT_MEMBER: 'TRANSFER_TARGET_NOT_MEMBER',
  // Admin
  ADMIN_MEMBER_NOT_FOUND: 'ADMIN_MEMBER_NOT_FOUND',
  ADMIN_ROLE_NOT_FOUND: 'ADMIN_ROLE_NOT_FOUND',
  MEMBER_ALREADY_EXISTS: 'MEMBER_ALREADY_EXISTS',
  INVITATION_ALREADY_PENDING: 'INVITATION_ALREADY_PENDING',
  LAST_OWNER_CONSTRAINT: 'LAST_OWNER_CONSTRAINT',
  SELF_REMOVAL: 'SELF_REMOVAL',
  SELF_ROLE_CHANGE: 'SELF_ROLE_CHANGE',
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
  // Admin Phase 2
  ADMIN_USER_NOT_FOUND: 'ADMIN_USER_NOT_FOUND',
  USER_ALREADY_BANNED: 'USER_ALREADY_BANNED',
  EMAIL_CONFLICT: 'EMAIL_CONFLICT',
  ADMIN_ORG_NOT_FOUND: 'ADMIN_ORG_NOT_FOUND',
  ADMIN_ORG_SLUG_CONFLICT: 'ADMIN_ORG_SLUG_CONFLICT',
  ADMIN_ORG_DEPTH_EXCEEDED: 'ADMIN_ORG_DEPTH_EXCEEDED',
  ADMIN_ORG_CYCLE_DETECTED: 'ADMIN_ORG_CYCLE_DETECTED',
  SELF_ACTION: 'SELF_ACTION',
  SUPERADMIN_PROTECTION: 'SUPERADMIN_PROTECTION',
  LAST_SUPERADMIN: 'LAST_SUPERADMIN',
  NOT_DELETED: 'NOT_DELETED',
  INVALID_CURSOR: 'INVALID_CURSOR',
  // API Keys
  API_KEY_NOT_FOUND: 'API_KEY_NOT_FOUND',
  API_KEY_SCOPES_EXCEEDED: 'API_KEY_SCOPES_EXCEEDED',
  API_KEY_EXPIRY_IN_PAST: 'API_KEY_EXPIRY_IN_PAST',
  API_KEY_INVALID: 'API_KEY_INVALID',
  API_KEY_REVOKED: 'API_KEY_REVOKED',
  API_KEY_EXPIRED: 'API_KEY_EXPIRED',
  API_KEY_UNAUTHORIZED: 'API_KEY_UNAUTHORIZED',
  API_KEY_SCOPE_DENIED: 'API_KEY_SCOPE_DENIED',
  API_KEY_REQUIRED: 'API_KEY_REQUIRED',
  // Admin Phase 3
  SETTING_NOT_FOUND: 'SETTING_NOT_FOUND',
  SETTING_VALIDATION: 'SETTING_VALIDATION',
  FEATURE_FLAG_NOT_FOUND: 'FEATURE_FLAG_NOT_FOUND',
  FEATURE_FLAG_KEY_CONFLICT: 'FEATURE_FLAG_KEY_CONFLICT',
  FEATURE_FLAG_KEY_INVALID: 'FEATURE_FLAG_KEY_INVALID',
  FEATURE_FLAG_CREATE_FAILED: 'FEATURE_FLAG_CREATE_FAILED',
  // Rate Limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
} as const

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode]
